<?php

namespace Ais\JadwalBundle\Repository;

/**
 * JadwalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JadwalRepository extends \Doctrine\ORM\EntityRepository
{
}
